# TMUX Configuration file.

# Remove old prefix key
unbind C-b

# New prefix key
set -g prefix C-Space
bind C-Space send-prefix

# Vim motion between windows.
bind M-h previous-window
bind M-l next-window

# Vim motion between panes.
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
